version: '3.8'
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    volumes:
      - type: bind
        source: ./local/emails
        target: /site_config
    ports:
      - "7778:7778"
    command: [
      "--provider=github",
      "--upstream=http://localhost:7777/#/",
      "--http-address=:7778",
      "--authenticated-emails-file=/site_config/email_list.txt",
      "--scope=user:email",
      "--cookie-expire=0h0m30s",
      "--session-cookie-minimal=true",
      "--skip-provider-button=true",
      "--cookie-secret=",
      "--client-id=",
      "--client-secret=",
      "--cookie-csrf-per-request=true",
      "--redirect-url=http://localhost:7777/#/",
      "--cookie-secure=false",
      "--cookie-csrf-expire=5m"
    ]
    restart: unless-stopped
